#include "keymap.h"

const char KEYMAP[NUM_ROWS][NUM_COLS] PROGMEM = {
	{HID_KEYBOARD_SC_I, HID_KEYBOARD_SC_L},
	{HID_KEYBOARD_SC_J, HID_KEYBOARD_SC_K}
};

//		#define HID_KEYBOARD_SC_1_AND_EXCLAMATION			0x1E
//		#define HID_KEYBOARD_SC_2_AND_AT				0x1F
//		#define HID_KEYBOARD_SC_3_AND_HASHMARK				0x20
//		#define HID_KEYBOARD_SC_4_AND_DOLLAR				0x21
//		#define HID_KEYBOARD_SC_5_AND_PERCENTAGE			0x22
//		#define HID_KEYBOARD_SC_6_AND_CARET				0x23
//		#define HID_KEYBOARD_SC_7_AND_AMPERSAND				0x24
//		#define HID_KEYBOARD_SC_8_AND_ASTERISK				0x25
//		#define HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS		0x26
//		#define HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS		0x27
//		#define HID_KEYBOARD_SC_ENTER					0x28
//		#define HID_KEYBOARD_SC_ESCAPE					0x29
//		#define HID_KEYBOARD_SC_BACKSPACE				0x2A
//		#define HID_KEYBOARD_SC_TAB					0x2B
//		#define HID_KEYBOARD_SC_SPACE					0x2C
//		#define HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE			0x2D
//		#define HID_KEYBOARD_SC_EQUAL_AND_PLUS				0x2E
//		#define HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE	0x2F
//		#define HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE	0x30
//		#define HID_KEYBOARD_SC_BACKSLASH_AND_PIPE			0x31
//		#define HID_KEYBOARD_SC_NON_US_HASHMARK_AND_TILDE		0x32
//		#define HID_KEYBOARD_SC_SEMICOLON_AND_COLON			0x33
//		#define HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE			0x34
//		#define HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE			0x35
//		#define HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN		0x36
//		#define HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN		0x37
//		#define HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK			0x38
//		#define HID_KEYBOARD_SC_CAPS_LOCK				0x39
//		#define HID_KEYBOARD_SC_F1					0x3A
//		#define HID_KEYBOARD_SC_F2					0x3B
//		#define HID_KEYBOARD_SC_F3					0x3C
//		#define HID_KEYBOARD_SC_F4					0x3D
//		#define HID_KEYBOARD_SC_F5					0x3E
//		#define HID_KEYBOARD_SC_F6					0x3F
//		#define HID_KEYBOARD_SC_F7					0x40
//		#define HID_KEYBOARD_SC_F8					0x41
//		#define HID_KEYBOARD_SC_F9					0x42
//		#define HID_KEYBOARD_SC_F10					0x43
//		#define HID_KEYBOARD_SC_F11					0x44
//		#define HID_KEYBOARD_SC_F12					0x45
//		#define HID_KEYBOARD_SC_PRINT_SCREEN				0x46
//		#define HID_KEYBOARD_SC_SCROLL_LOCK				0x47
//		#define HID_KEYBOARD_SC_PAUSE					0x48
//		#define HID_KEYBOARD_SC_INSERT					0x49
//		#define HID_KEYBOARD_SC_HOME					0x4A
//		#define HID_KEYBOARD_SC_PAGE_UP					0x4B
//		#define HID_KEYBOARD_SC_DELETE					0x4C
//		#define HID_KEYBOARD_SC_END					0x4D
//		#define HID_KEYBOARD_SC_PAGE_DOWN				0x4E
//		#define HID_KEYBOARD_SC_RIGHT_ARROW				0x4F
//		#define HID_KEYBOARD_SC_LEFT_ARROW				0x50
//		#define HID_KEYBOARD_SC_DOWN_ARROW				0x51
//		#define HID_KEYBOARD_SC_UP_ARROW				0x52
//		#define HID_KEYBOARD_SC_NUM_LOCK				0x53
//		#define HID_KEYBOARD_SC_KEYPAD_SLASH				0x54
//		#define HID_KEYBOARD_SC_KEYPAD_ASTERISK				0x55
//		#define HID_KEYBOARD_SC_KEYPAD_MINUS				0x56
//		#define HID_KEYBOARD_SC_KEYPAD_PLUS				0x57
//		#define HID_KEYBOARD_SC_KEYPAD_ENTER				0x58
//		#define HID_KEYBOARD_SC_KEYPAD_1_AND_END			0x59
//		#define HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW			0x5A
//		#define HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN			0x5B
//		#define HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW			0x5C
//		#define HID_KEYBOARD_SC_KEYPAD_5				0x5D
//		#define HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW		0x5E
//		#define HID_KEYBOARD_SC_KEYPAD_7_AND_HOME			0x5F
//		#define HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW			0x60
//		#define HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP			0x61
//		#define HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT			0x62
//		#define HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE			0x63
//		#define HID_KEYBOARD_SC_NON_US_BACKSLASH_AND_PIPE		0x64
//