#include "keymap.h"

const char KEYMAP[NUM_ROWS][NUM_COLS] PROGMEM = {
	{HID_MEDIACONTROLLER_SC_REWIND, HID_MEDIACONTROLLER_SC_FAST_FORWARD},
	{HID_MEDIACONTROLLER_SC_VOLUME_DOWN, HID_MEDIACONTROLLER_SC_VOLUME_UP}
};

