#include "keymap.h"

// The key map array.
const char KEYMAP[NUM_KEYS] PROGMEM = {
	HID_MEDIACONTROLLER_SC_TOGGLE,		// Key 1
	HID_MEDIACONTROLLER_SC_STOP,		// Key 2
	HID_MEDIACONTROLLER_SC_PREVIOUS,	// Key 3
	HID_MEDIACONTROLLER_SC_NEXT		// Key 4
};
